name = "gem-id-vn"
account_id = "bbef1813ec9b7d5f8fa24e49120f64ee"
workers_dev = false
main = "src/api/index.ts"
compatibility_date = "2024-06-01"

# ✅ Sử dụng route gốc, không cần route ngẫu nhiên
routes = [ "https://gem.id.vn/api/qs8mjlxheo8zb703dzubdzx20521qj" ]

[build]
command = ""
upload.format = "modules"
upload.main = "src/api/index.ts"

kv_namespaces = [
  { binding = "KHOAI_KV_USER",     id = "77a8867cc9374bbaa9846d78875efbf0" },
  { binding = "KHOAI_KV_COOKIE",   id = "9e0fee27605645ae9b60157f6e75e4e7" },
  { binding = "KHOAI_KV_API_KEY",  id = "be4985203f4445b1b9b9b92fcae18a16" },
  { binding = "KHOAI_KV_ROUTE",    id = "8923fac56d1b42528f76d13ba473fe68" },
  { binding = "KHOAI_KV_LOGGER",   id = "056e31b4339648ecae8ccc88e4cbfa6a" },
  { binding = "KHOAI_KV_OUTLOOK",  id = "60ad76d205ff435c8101bd3e31428a01" },
  { binding = "KHOAI_KV_GMAIL",    id = "08b95e1748744c80b9f797d3c0d4fe4b" }
]

[vars]
ENVIRONMENT = "production"
