name = "gem-id-vn"
main = "dist/worker.js"        
compatibility_date = "2024-06-27"

# KV Bindings
[[kv_namespaces]]
binding = "KHOAI_KV_USER"
id = "77a8867cc9374bbaa9846d78875efbf0"
preview_id = "77a8867cc9374bbaa9846d78875efbf0"

[[kv_namespaces]]
binding = "KHOAI_KV_TOKEN"
id = "f6f5eef5735443e685d45c500f06df83"
preview_id = "f6f5eef5735443e685d45c500f06df83"

[[kv_namespaces]]
binding = "KHOAI_KV_OUTLOOK"
id = "60ad76d205ff435c8101bd3e31428a01"
preview_id = "60ad76d205ff435c8101bd3e31428a01"

[[kv_namespaces]]
binding = "KHOAI_KV_GMAIL"
id = "08b95e1748744c80b9f797d3c0d4fe4b"
preview_id = "08b95e1748744c80b9f797d3c0d4fe4b"

[[kv_namespaces]]
binding = "KHOAI_KV_COIN"
id = "44498515d40948d7b12072b677cf5cb7"
preview_id = "44498515d40948d7b12072b677cf5cb7"

[[kv_namespaces]]
binding = "KHOAI_KV_LOGGER_COIN"
id = "852f904fc9384926be284eefacf15cd2"
preview_id = "bbef1813ec9b7d5f8fa24e49120f64ee"

[[kv_namespaces]]
binding = "KHOAI_KV_SETTING"
id = "36725c9be54a41a6b06773c90586a8d1"
preview_id = "36725c9be54a41a6b06773c90586a8d1"

# Thêm các KV khác nếu cần...

# Static Site (nếu có UI static kèm Worker, ví dụ /public)
[site]
bucket = "./public"

# Route production (ví dụ subdomain hoặc domain chính)
# routes = [
#   { pattern = "gem.id.vn/*", zone_id = "xxxx" }
# ]

[build]
command = "npm run build"
watch_dir = "src"

# Environment (tùy chỉnh môi trường nếu cần)
[env.production]
# environment-specific settings
